### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Jane-Tran** [Romansko/SignLanguageRecognition#3]
Can you share the training data, I tried to find but the link is dead.
Ths Bro

**Comment by kernkernkern** [comment]
> Can you share the training data, I tried to find but the link is dead.
> Ths Bro

Hey Jane-Tran have you succeeded in getting the training data?

**Comment by Jane-Tran** [comment]
> Hey Jane-Tran have you succeeded in getting the training data?
I found it from another source:
https://www.kaggle.com/grassknoted/asl-alphabet?
